### ISSUE TITLE
Numeric Ramp: line-color

### ISSUE THREAD

**Issue by makella** [CartoDB/turbo-carto#12]
hi!
I was making a bivariate point map of earthquakes in Nepal where the symbol size is based on the magnitude and the line color, based on the depth. I've forced the `line-width` to 3 buckets, but I'm seeing 5.

Here is the map with the 5 outline classes labeled (its hard to see the lightest color against the background):

<img width="721" alt="screen shot 2016-03-16 at 5 32 25 pm" src="https://cloud.githubusercontent.com/assets/1566273/13831950/214347fc-eb9d-11e5-84c6-c4efc3b8cbb7.png">

And here's my **TURBO** :) cartocss
```
#layer {
  marker-placement: point;
  marker-allow-overlap: true;
  marker-line-opacity: 1;
  marker-line-width: 3;
  marker-line-color: ramp([depth],colorbrewer(PuRd),3);
  marker-opacity: 1;
  marker-fill: #000;
  marker-fill-opacity: 0.5;
  marker-width: ramp([mag], 6, 24, 5);
}
```

**Comment by rochoa** [comment]
Just in case: to set the number of buckets in color brewer you need to do it in the colorbrewer function: https://github.com/CartoDB/turbo-cartocss/blob/6999d2900ad52af3054ec986cc620062b2a45d9a/docs/quickstart.md#change-number-of-color-brewer-data-classes :-)

**Comment by makella** [comment]
oops! ugh, sorry. missed that detail
