### ISSUE TITLE
mapnik::geometry-type instead of mapnik.geometry-type

### ISSUE THREAD

**Issue by javisantana** [CartoDB/turbo-carto#16]
Why do we do that? should be add support to carto parser to this variable?

it's failing in the current cartodb editor

**Comment by rochoa** [comment]
turbo-carto has nothing to do with that kind of cartocss.

It looks it something within cartodb default style: https://github.com/CartoDB/cartodb/blob/30aae404bc2ba5b857bf1127817b596e790c795b/lib/assets/javascripts/cartodb3/data/camshaft-reference.js#L46-L72

**Comment by javisantana** [comment]
oops, sorry
