### ISSUE TITLE
Generated CartoCSS from ramp function is appended at the end of the layer

### ISSUE THREAD

**Issue by saleiva** [CartoDB/turbo-carto#20]
So order is ignored which is bad.

If writting:
marker-width: ramp([price_per_sqmeter], 3, 48, 7, jenks);
marker-width: 1;

I'd expect
marker-width[x>y]{..}
marker-width[x>y1]{..}
marker-width[x>y2]{..}
marker-width: 1

But the actual behaviour gives:
marker-width: 1
marker-width[x>y]{..}
marker-width[x>y1]{..}
marker-width[x>y2]{..}

**Comment by makella** [comment]
@saleiva where are you accessing the output cartocss?? I want to see!!

**Comment by saleiva** [comment]
You can see it at the map? request using the web developer tools :)

2016-05-05 20:00 GMT+02:00 Mamata Akella <notifications@github.com>:

> @saleiva <https://github.com/saleiva> where are you accessing the output
> cartocss?? I want to see!!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/turbo-carto/issues/20#issuecomment-217227182>
>



-- 
Sergio Alvarez Leiva
