### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by rochoa** [CartoDB/turbo-carto#8]
Avoid using cartocss in the name.

**Comment by rochoa** [comment]
cc @makella

**Comment by javisantana** [comment]
My proposals
- turbocarto 
- carto++
- cartovis

**Comment by javisantana** [comment]
please, lets try to do ASAP before we start to use this everywhere

**Comment by makella** [comment]
nice ones! i'm trying to think what is easiest to say and that also sounds like a styling language. i like  carto++ and cartovis but maybe carto4vis or something. or maybe drop carto and call it turboviz? or is the carto part needed for cartobd?

this is a hard one.

**Comment by rochoa** [comment]
I just renamed it to turbo-carto 📦 . Published to npm registry.

I will update the places where we are already using it.
